name:                Traversable 
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- hspec
- QuickCheck
- checkers

library:
  source-dirs: src

tests:
  Foldable-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies:
    - Traversable 
